name = "testdeployurl8"
main = "workers/app.ts"
compatibility_date = "2025-10-23"

# Account ID - uses CLOUDFLARE_ACCOUNT_ID from GitHub secrets by default
account_id = "6ec57290cbb52c27cda0bd089bae05a0"

# Optional configuration:
# workers_dev = true
# route = "example.com/*"
# zone_id = "<your-zone-id>"

[env.preview]
name = "testdeployurl8-preview"

# Add bindings as needed:
# [[kv_namespaces]]
# binding = "MY_KV"
# id = "<kv-namespace-id>"

# [[d1_databases]]
# binding = "MY_DB"
# database_id = "<d1-database-id>"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "<r2-bucket-name>"
